baseURL: http://45.89.107.9/
languageCode: en-au
title: The Wandering Glitch
theme: ananke
resourceDir: ../resources

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 5 
googleAnalytics: 
enableRobotsTXT: true

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

params:
  text_color: "#000000"
  author: 
  favicon: 
  site_logo: 
  description: All the amusing things
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with bg-
  background_color_class: bg-black
  recent_posts_number: 10
  omit_header_text: true
  ananke_socials:
  - name: twitter
    url: https://twitter.com/aabs
  - name: github
    url: https://github.com/aabs
  - name: mastadon
    url: https://techhub.social/@aabs
    rel: me noopener
