
baseURL: https://industrialinference.com
title: Industrial Inference
theme: whiteplain
params:
  author:
    name: "Andrew Matthews"
    gravatar: "matthews.andrew@gmail.com"
    twitter: "aabs"
    facebook: "aabsinoz"
    googleplus: "matthews.andrew"
    instagram: "aabsinoz"
    flickr: "aabsinoz"
    reddit: "aabs"
    linkedin: "andrewmatthews"
    github: "aabs"
    bitbucket: "aabs"
    stackoverflow: "andrew-matthews"
    wordpress: "aabs"
    quora: "Andrew-Matthews-1"
    youtube: "matthews.andrew"
    email: "matthews.andrew@gmail.com"
  AuthorName: Andrew Matthews
  show_reading_time: true
  showShareIcons: true
  dateFormat: "January 2, 2006"
  SidebarRecentLimit: 5
permalinks:
  posts: /:year/:month/:title/
copyright: Andrew Matthews

taxonomies:
  tag: "tags"
  series: "series"

# Header Menu
menu:
  main:
  - name: "Series"
    identifier: "series"
    url: "/series/"
    weight: 1
  - name: "Tags"
    identifier: "tags"
    url: "/tags/"
    weight: 2
  - name: "Archives"
    identifier: "archives"
    url: "/archives/"
    weight: 3
  - name: "About"
    identifier: "about"
    url: "/about/"
    weight: 4
