
baseURL: https://industrialinference.com
title: The Wandering Glitch
theme: hugo-coder
params:
  AuthorName: Andrew Matthews
  GitHubUser: aabs
  themeColor: pink
  fullWidthTheme: false
  centerTheme: true
  autoCover: true
  show_reading_time: true
  SidebarRecentLimit: 5
  Subtitle: All the amusing things...
  ananke_socials:
  - name: twitter
    url: https://twitter.com/aabs
  - name: github
    url: https://github.com/aabs
  - name: mastadon
    url: https://techhub.social/@aabs
    rel: me noopener
permalinks:
  posts: /:year/:month/:title/
copyright: Andrew Matthews